#include "../../framework/unity.h"
#include "../../../kernel/net_http_tls.h"

void setUp(void) {}
void tearDown(void) {}

static void open_pair(net_tcp_connection_t* client,net_tcp_connection_t* server,net_tls_aes_gcm_session_t* client_session,net_tls_aes_gcm_session_t* server_session,uint8_t key_material[40]){
    net_tcp_view_t syn_ack;net_tls_aes128_gcm_key_block_t block;uint8_t i;
    for(i=0U;i<40U;i++)key_material[i]=(uint8_t)(i+1U);
    block=(net_tls_aes128_gcm_key_block_t){key_material,key_material+16U,key_material+32U,key_material+36U};
    TEST_ASSERT_EQUAL(0,net_tls_aes_gcm_session_init(client_session,&block,1U));
    TEST_ASSERT_EQUAL(0,net_tls_aes_gcm_session_init(server_session,&block,0U));
    TEST_ASSERT_EQUAL(0,net_tcp_connection_open(client,49152U,443U,100U));
    syn_ack=(net_tcp_view_t){443U,49152U,700U,101U,NET_TCP_FLAG_SYN|NET_TCP_FLAG_ACK,0,0};
    TEST_ASSERT_EQUAL(0,net_tcp_connection_accept_syn_ack(client,&syn_ack));
    TEST_ASSERT_EQUAL(0,net_tcp_connection_open(server,443U,49152U,700U));
    syn_ack=(net_tcp_view_t){49152U,443U,100U,701U,NET_TCP_FLAG_SYN|NET_TCP_FLAG_ACK,0,0};
    TEST_ASSERT_EQUAL(0,net_tcp_connection_accept_syn_ack(server,&syn_ack));
}

void test_http_tls_get_and_response(void){
    net_tcp_connection_t client,server;net_tls_aes_gcm_session_t client_session,server_session;net_tcp_view_t view;net_tls_record_view_t record;net_http_response_view_t response;uint8_t key_material[40]={0},tcp_segment[192]={0},tls_record[160]={0},request[128]={0},plaintext[160]={0},response_record[160]={0},response_segment[192]={0},response_text[]={ 'H','T','T','P','/','1','.','1',' ','2','0','0',' ','O','K','\r','\n','C','o','n','n','e','c','t','i','o','n',':',' ','c','l','o','s','e','\r','\n','\r','\n','o','k'};uint16_t consumed=0U;int length;
    open_pair(&client,&server,&client_session,&server_session,key_material);
    TEST_ASSERT_EQUAL(70,net_http_build_get(request,sizeof(request),"api.example.test","/v1/models"));
    TEST_ASSERT_EQUAL('G',request[0]);TEST_ASSERT_EQUAL('/',request[4]);TEST_ASSERT_EQUAL('H',request[15]);
    length=net_http_tls_build_get(&client,&client_session,tcp_segment,sizeof(tcp_segment),tls_record,sizeof(tls_record),request,sizeof(request),"api.example.test","/v1/models",1U);
    TEST_ASSERT_EQUAL(119,length);TEST_ASSERT_EQUAL(0,net_tcp_parse(tcp_segment,(uint16_t)length,&view));
    TEST_ASSERT_EQUAL(0,net_tcp_connection_accept_tls_aes_gcm(&server,&server_session,&view,plaintext,sizeof(plaintext),&record,&consumed));
    TEST_ASSERT_EQUAL(70,record.payload_length);TEST_ASSERT_EQUAL('G',plaintext[0]);TEST_ASSERT_EQUAL('T',plaintext[2]);TEST_ASSERT_EQUAL('H',plaintext[15]);
    TEST_ASSERT_EQUAL(0,net_tcp_connection_commit_send(&client,view.payload_length));
    length=net_tcp_connection_build_tls_aes_gcm(&server,&server_session,response_segment,sizeof(response_segment),response_record,sizeof(response_record),NET_TLS_CONTENT_APPLICATION_DATA,response_text,sizeof(response_text),1U);
    TEST_ASSERT_EQUAL(89,length);TEST_ASSERT_EQUAL(0,net_tcp_parse(response_segment,(uint16_t)length,&view));
    TEST_ASSERT_EQUAL(0,net_http_tls_open_response(&client,&client_session,&view,plaintext,sizeof(plaintext),&response,&consumed));
    TEST_ASSERT_EQUAL(200,response.status_code);TEST_ASSERT_EQUAL(2,response.body_length);TEST_ASSERT_EQUAL('o',response.body[0]);TEST_ASSERT_EQUAL('k',response.body[1]);
}

void test_http_post_json_build_and_bounds(void){
    static const uint8_t json[]={ '{','"','m','o','d','e','l','"',':','"','g','p','t','2','"',',','"','p','r','o','m','p','t','"',':','"','h','i','"','}' };
    static const uint8_t expected[]="POST /v1/completions HTTP/1.1\r\nHost: api.example.test\r\nContent-Type: application/json\r\nContent-Length: 30\r\nConnection: close\r\n\r\n{\"model\":\"gpt2\",\"prompt\":\"hi\"}";
    uint8_t request[192]={0};
    TEST_ASSERT_EQUAL((int)(sizeof(expected)-1U),net_http_build_post_json(request,sizeof(request),"api.example.test","/v1/completions",json,sizeof(json)));
    TEST_ASSERT_EQUAL_MEMORY(expected,request,sizeof(expected)-1U);
    TEST_ASSERT_NOT_EQUAL(0,net_http_build_post_json(request,12U,"api.example.test","/v1/completions",json,sizeof(json)));
    TEST_ASSERT_NOT_EQUAL(0,net_http_build_post_json(request,sizeof(request),"api.example.test","v1/completions",json,sizeof(json)));
    TEST_ASSERT_NOT_EQUAL(0,net_http_build_post_json(request,sizeof(request),"api.example.test","/v1/completions",0,1U));
}

void test_http_post_json_bearer_build_and_bounds(void){static const uint8_t json[]={'{','"','m','o','d','e','l','"',':','"','g','p','t','2','"','}'};static const uint8_t expected[]="POST /v1/completions HTTP/1.1\r\nHost: api.example.test\r\nAuthorization: Bearer sk-test-123\r\nContent-Type: application/json\r\nContent-Length: 16\r\nConnection: close\r\n\r\n{\"model\":\"gpt2\"}";uint8_t request[224]={0};TEST_ASSERT_EQUAL((int)(sizeof(expected)-1U),net_http_build_post_json_bearer(request,sizeof(request),"api.example.test","/v1/completions","sk-test-123",json,sizeof(json)));TEST_ASSERT_EQUAL_MEMORY(expected,request,sizeof(expected)-1U);TEST_ASSERT_NOT_EQUAL(0,net_http_build_post_json_bearer(request,sizeof(request),"api.example.test","/v1/completions","",json,sizeof(json)));TEST_ASSERT_NOT_EQUAL(0,net_http_build_post_json_bearer(request,16U,"api.example.test","/v1/completions","sk-test-123",json,sizeof(json)));}

void test_http_tls_post_json_encrypted(void){
    net_tcp_connection_t client,server;net_tls_aes_gcm_session_t client_session,server_session;net_tcp_view_t view;net_tls_record_view_t record;
    static const uint8_t json[]={ '{','"','m','o','d','e','l','"',':','"','g','p','t','2','"',',','"','p','r','o','m','p','t','"',':','"','h','i','"','}' };
    static const uint8_t expected[]="POST /v1/completions HTTP/1.1\r\nHost: api.example.test\r\nContent-Type: application/json\r\nContent-Length: 30\r\nConnection: close\r\n\r\n{\"model\":\"gpt2\",\"prompt\":\"hi\"}";
    uint8_t key_material[40]={0},tcp_segment[256]={0},tls_record[224]={0},request[192]={0},plaintext[192]={0};uint16_t consumed=0U;int length;
    open_pair(&client,&server,&client_session,&server_session,key_material);
    length=net_http_tls_build_post_json(&client,&client_session,tcp_segment,sizeof(tcp_segment),tls_record,sizeof(tls_record),request,sizeof(request),"api.example.test","/v1/completions",json,sizeof(json),1U);
    TEST_ASSERT_EQUAL((int)(20U+5U+8U+sizeof(expected)-1U+16U),length);TEST_ASSERT_EQUAL(1,client_session.write_sequence);
    TEST_ASSERT_EQUAL(0,net_tcp_parse(tcp_segment,(uint16_t)length,&view));
    TEST_ASSERT_EQUAL(0,net_tcp_connection_accept_tls_aes_gcm(&server,&server_session,&view,plaintext,sizeof(plaintext),&record,&consumed));
    TEST_ASSERT_EQUAL(sizeof(expected)-1U,record.payload_length);TEST_ASSERT_EQUAL_MEMORY(expected,plaintext,sizeof(expected)-1U);TEST_ASSERT_EQUAL(1,server_session.read_sequence);
}

void test_http_tls_response_stream_content_length(void){net_tcp_connection_t client,server;net_tls_aes_gcm_session_t client_session,server_session;net_tcp_view_t view;net_http_response_accumulator_t accumulator;net_http_response_view_t response;uint8_t key_material[40]={0},first_segment[128]={0},second_segment[96]={0},first_record[96]={0},second_record[64]={0},plaintext[96]={0},response_buffer[96]={0},first_response[]={ 'H','T','T','P','/','1','.','1',' ','2','0','0',' ','O','K','\r','\n','C','o','n','t','e','n','t','-','L','e','n','g','t','h',':',' ','5','\r','\n','\r','\n','h','e'},second_response[]={ 'l','l','o'};uint16_t consumed=0U;int length;open_pair(&client,&server,&client_session,&server_session,key_material);TEST_ASSERT_EQUAL(0,net_http_response_accumulator_init(&accumulator,response_buffer,sizeof(response_buffer)));length=net_tcp_connection_build_tls_aes_gcm(&server,&server_session,first_segment,sizeof(first_segment),first_record,sizeof(first_record),NET_TLS_CONTENT_APPLICATION_DATA,first_response,sizeof(first_response),1U);TEST_ASSERT_EQUAL(89,length);TEST_ASSERT_EQUAL(0,net_tcp_parse(first_segment,(uint16_t)length,&view));TEST_ASSERT_EQUAL(1,net_http_tls_open_response_stream(&client,&client_session,&view,plaintext,sizeof(plaintext),&accumulator,&response,&consumed));TEST_ASSERT_EQUAL(sizeof(first_response),accumulator.length);TEST_ASSERT_EQUAL(1,accumulator.headers_complete);TEST_ASSERT_EQUAL(1,client_session.read_sequence);TEST_ASSERT_EQUAL(0,net_tcp_connection_commit_send(&server,69U));length=net_tcp_connection_build_tls_aes_gcm(&server,&server_session,second_segment,sizeof(second_segment),second_record,sizeof(second_record),NET_TLS_CONTENT_APPLICATION_DATA,second_response,sizeof(second_response),1U);TEST_ASSERT_EQUAL(52,length);TEST_ASSERT_EQUAL(0,net_tcp_parse(second_segment,(uint16_t)length,&view));TEST_ASSERT_EQUAL(0,net_http_tls_open_response_stream(&client,&client_session,&view,plaintext,sizeof(plaintext),&accumulator,&response,&consumed));TEST_ASSERT_EQUAL(200,response.status_code);TEST_ASSERT_EQUAL(5,response.body_length);TEST_ASSERT_EQUAL('h',response.body[0]);TEST_ASSERT_EQUAL('o',response.body[4]);TEST_ASSERT_EQUAL(2,client_session.read_sequence);}
void test_http_chunked_accumulator_fragmented(void){net_http_chunked_accumulator_t accumulator;net_http_response_view_t response;uint8_t buffer[128]={0};uint8_t first[]="HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\n\r\n4\r\nWi";uint8_t second[]="ki\r\n5\r\npedia\r\n0\r\n\r\n";uint8_t invalid[]="HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\n\r\nZ\r\n";TEST_ASSERT_EQUAL(0,net_http_chunked_accumulator_init(&accumulator,buffer,sizeof(buffer)));TEST_ASSERT_EQUAL(1,net_http_chunked_accumulator_feed(&accumulator,first,sizeof(first)-1U,&response));TEST_ASSERT_EQUAL(0,net_http_chunked_accumulator_feed(&accumulator,second,sizeof(second)-1U,&response));TEST_ASSERT_EQUAL(200,response.status_code);TEST_ASSERT_EQUAL(9,response.body_length);TEST_ASSERT_EQUAL_MEMORY("Wikipedia",response.body,9U);TEST_ASSERT_EQUAL(0,net_http_chunked_accumulator_init(&accumulator,buffer,sizeof(buffer)));TEST_ASSERT_NOT_EQUAL(0,net_http_chunked_accumulator_feed(&accumulator,invalid,sizeof(invalid)-1U,&response));}

void test_llm_json_string_extract(void){uint8_t output[32]={0};uint16_t length=0U;static const uint8_t json[]="{\"model\":\"gpt2\",\"response\":\"hello\\nworld\"}";static const uint8_t unicode[]="{\"response\":\"\\u0041\"}";TEST_ASSERT_EQUAL(0,net_json_extract_string(json,sizeof(json)-1U,"response",output,sizeof(output),&length));TEST_ASSERT_EQUAL(11,length);TEST_ASSERT_EQUAL_MEMORY("hello\nworld",output,11U);TEST_ASSERT_NOT_EQUAL(0,net_json_extract_string(json,sizeof(json)-1U,"missing",output,sizeof(output),&length));TEST_ASSERT_EQUAL(0,net_json_extract_string(unicode,sizeof(unicode)-1U,"response",output,sizeof(output),&length));TEST_ASSERT_EQUAL(1U,length);TEST_ASSERT_EQUAL('A',output[0]);TEST_ASSERT_NOT_EQUAL(0,net_json_extract_string(json,sizeof(json)-1U,"response",output,4U,&length));}

void test_llm_provider_response_adapters(void){uint8_t output[32]={0};uint16_t length=0U;static const uint8_t ollama[]="{\"model\":\"tinyllama\",\"response\":\"bonjour\",\"done\":true}";static const uint8_t openai[]="{\"choices\":[{\"message\":{\"role\":\"assistant\",\"content\":\"salut\"}}]}";TEST_ASSERT_EQUAL(0,net_llm_ollama_response_extract(ollama,sizeof(ollama)-1U,output,sizeof(output),&length));TEST_ASSERT_EQUAL(7,length);TEST_ASSERT_EQUAL_MEMORY("bonjour",output,7U);TEST_ASSERT_EQUAL(0,net_llm_openai_response_extract(openai,sizeof(openai)-1U,output,sizeof(output),&length));TEST_ASSERT_EQUAL(5,length);TEST_ASSERT_EQUAL_MEMORY("salut",output,5U);TEST_ASSERT_NOT_EQUAL(0,net_llm_ollama_response_extract(openai,sizeof(openai)-1U,output,sizeof(output),&length));TEST_ASSERT_NOT_EQUAL(0,net_llm_openai_response_extract(ollama,sizeof(ollama)-1U,output,sizeof(output),&length));}

void test_llm_request_json_builders(void){uint8_t output[192]={0};static const uint8_t prompt[]={'s','a','l','u','t',' ','"','x','"','\n'};static const uint8_t control[]={'a',1U};static const uint8_t ollama[]="{\"model\":\"tinyllama\",\"prompt\":\"salut \\\"x\\\"\\n\",\"stream\":false}";static const uint8_t openai[]="{\"model\":\"gpt-4o-mini\",\"messages\":[{\"role\":\"user\",\"content\":\"salut \\\"x\\\"\\n\"}],\"stream\":false}";TEST_ASSERT_EQUAL((int)(sizeof(ollama)-1U),net_llm_build_ollama_generate_json(output,sizeof(output),"tinyllama",prompt,sizeof(prompt)));TEST_ASSERT_EQUAL_MEMORY(ollama,output,sizeof(ollama)-1U);TEST_ASSERT_EQUAL((int)(sizeof(openai)-1U),net_llm_build_openai_chat_json(output,sizeof(output),"gpt-4o-mini",prompt,sizeof(prompt)));TEST_ASSERT_EQUAL_MEMORY(openai,output,sizeof(openai)-1U);TEST_ASSERT_NOT_EQUAL(0,net_llm_build_ollama_generate_json(output,sizeof(output),"tinyllama",control,sizeof(control)));TEST_ASSERT_NOT_EQUAL(0,net_llm_build_openai_chat_json(output,8U,"gpt-4o-mini",prompt,sizeof(prompt)));}

void test_llm_http_status_and_retry_policy(void){uint8_t retries=0U;TEST_ASSERT_EQUAL(NET_LLM_HTTP_STATUS_SUCCESS,net_llm_http_status_classify(200U));TEST_ASSERT_EQUAL(NET_LLM_HTTP_STATUS_SUCCESS,net_llm_http_status_classify(299U));TEST_ASSERT_EQUAL(NET_LLM_HTTP_STATUS_AUTH,net_llm_http_status_classify(401U));TEST_ASSERT_EQUAL(NET_LLM_HTTP_STATUS_AUTH,net_llm_http_status_classify(403U));TEST_ASSERT_EQUAL(NET_LLM_HTTP_STATUS_RETRYABLE,net_llm_http_status_classify(408U));TEST_ASSERT_EQUAL(NET_LLM_HTTP_STATUS_RETRYABLE,net_llm_http_status_classify(429U));TEST_ASSERT_EQUAL(NET_LLM_HTTP_STATUS_RETRYABLE,net_llm_http_status_classify(503U));TEST_ASSERT_EQUAL(NET_LLM_HTTP_STATUS_PERMANENT,net_llm_http_status_classify(400U));TEST_ASSERT_EQUAL(NET_LLM_HTTP_STATUS_PERMANENT,net_llm_http_status_classify(302U));TEST_ASSERT_EQUAL(NET_LLM_HTTP_STATUS_PROTOCOL,net_llm_http_status_classify(0U));TEST_ASSERT_EQUAL(1,net_llm_http_retry_consume(503U,2U,&retries));TEST_ASSERT_EQUAL(1U,retries);TEST_ASSERT_EQUAL(1,net_llm_http_retry_consume(429U,2U,&retries));TEST_ASSERT_EQUAL(2U,retries);TEST_ASSERT_EQUAL(0,net_llm_http_retry_consume(500U,2U,&retries));TEST_ASSERT_EQUAL(0,net_llm_http_retry_consume(401U,2U,&retries));TEST_ASSERT_EQUAL(2U,retries);TEST_ASSERT_NOT_EQUAL(0,net_llm_http_retry_consume(503U,1U,0));}

void test_http_response_parse_rejects_invalid_framing(void){
    net_http_response_view_t response;uint8_t invalid[]={ 'N','O','T',' ','H','T','T','P','\r','\n','\r','\n'};uint8_t incomplete[]={ 'H','T','T','P','/','1','.','1',' ','2','0','0',' ','O','K','\r','\n'};
    TEST_ASSERT_NOT_EQUAL(0,net_http_response_parse(invalid,sizeof(invalid),&response));
    TEST_ASSERT_NOT_EQUAL(0,net_http_response_parse(incomplete,sizeof(incomplete),&response));
}

void test_llm_stream_json_and_sse_fragments(void){net_llm_sse_accumulator_t accumulator,tiny;uint8_t json[128]={0},buffer[96]={0},tiny_buffer[4]={0},text[32]={0};uint16_t text_length=0U;static const uint8_t ollama[]="{\"model\":\"tinyllama\",\"prompt\":\"hi\",\"stream\":true}";static const uint8_t openai[]="{\"model\":\"gpt-4o-mini\",\"messages\":[{\"role\":\"user\",\"content\":\"hi\"}],\"stream\":true}";TEST_ASSERT_EQUAL((int)(sizeof(ollama)-1U),net_llm_build_ollama_generate_stream_json(json,sizeof(json),"tinyllama",(const uint8_t*)"hi",2U));TEST_ASSERT_EQUAL_MEMORY(ollama,json,sizeof(ollama)-1U);TEST_ASSERT_EQUAL((int)(sizeof(openai)-1U),net_llm_build_openai_chat_stream_json(json,sizeof(json),"gpt-4o-mini",(const uint8_t*)"hi",2U));TEST_ASSERT_EQUAL_MEMORY(openai,json,sizeof(openai)-1U);TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_init(&accumulator,buffer,sizeof(buffer)));TEST_ASSERT_EQUAL(1,net_llm_sse_accumulator_feed(&accumulator,0U,(const uint8_t*)"data: {\"response\":\"bon",22U,text,sizeof(text),&text_length));TEST_ASSERT_EQUAL(0U,text_length);TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_feed(&accumulator,0U,(const uint8_t*)"jour\"}\n\ndata: [DONE]\n\n",22U,text,sizeof(text),&text_length));TEST_ASSERT_EQUAL(7U,text_length);TEST_ASSERT_EQUAL_MEMORY("bonjour",text,7U);TEST_ASSERT_EQUAL(1U,accumulator.done);TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_init(&tiny,tiny_buffer,sizeof(tiny_buffer)));TEST_ASSERT_NOT_EQUAL(0,net_llm_sse_accumulator_feed(&tiny,0U,(const uint8_t*)"data:",5U,text,sizeof(text),&text_length));TEST_ASSERT_NOT_EQUAL(0,net_llm_sse_accumulator_init(&accumulator,buffer,0U));TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_init(&accumulator,buffer,sizeof(buffer)));TEST_ASSERT_NOT_EQUAL(0,net_llm_sse_accumulator_feed(&accumulator,0U,(const uint8_t*)"event: bad\n\n",12U,text,sizeof(text),&text_length));}
void test_llm_sse_chunked_openai_response(void){net_llm_sse_response_t response;uint8_t http_buffer[160]={0},sse_buffer[96]={0},text[32]={0};uint16_t text_length=0U;static const uint8_t input[]="HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\n\r\n33\r\ndata: {\"choices\":[{\"delta\":{\"content\":\"salut\"}}]}\n\n\r\n0\r\n\r\n";TEST_ASSERT_EQUAL(0,net_llm_sse_response_init(&response,http_buffer,sizeof(http_buffer),sse_buffer,sizeof(sse_buffer)));TEST_ASSERT_EQUAL(0,net_llm_sse_response_feed(&response,1U,input,sizeof(input)-1U,text,sizeof(text),&text_length));TEST_ASSERT_EQUAL(5U,text_length);TEST_ASSERT_EQUAL_MEMORY("salut",text,5U);TEST_ASSERT_EQUAL(1U,response.http.state==8U);}
void test_llm_sse_chunked_ollama_incremental(void){
    net_llm_sse_response_t response;uint8_t http_buffer[160]={0},sse_buffer[96]={0},text[32]={0};uint16_t text_length=0U;
    static const uint8_t first[]="HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\n\r\n19\r\ndata: {\"response\":\"ok\"}\n\n\r\n";
    static const uint8_t second[]="e\r\ndata: [DONE]\n\n\r\n0\r\n\r\n";
    TEST_ASSERT_EQUAL(0,net_llm_sse_response_init(&response,http_buffer,sizeof(http_buffer),sse_buffer,sizeof(sse_buffer)));
    TEST_ASSERT_EQUAL(1,net_llm_sse_response_feed(&response,0U,first,sizeof(first)-1U,text,sizeof(text),&text_length));
    TEST_ASSERT_EQUAL(2U,text_length);TEST_ASSERT_EQUAL_MEMORY("ok",text,2U);
    TEST_ASSERT_EQUAL(0U,response.sse.done);TEST_ASSERT_NOT_EQUAL(8U,response.http.state);
    TEST_ASSERT_EQUAL(0,net_llm_sse_response_feed(&response,0U,second,sizeof(second)-1U,text,sizeof(text),&text_length));
    TEST_ASSERT_EQUAL(0U,text_length);TEST_ASSERT_EQUAL(1U,response.sse.done);TEST_ASSERT_EQUAL(8U,response.http.state);
}
void test_llm_sse_second_stream_after_reinit(void){
    net_llm_sse_response_t response;uint8_t http_buffer[160]={0},sse_buffer[96]={0},text[32]={0};uint16_t text_length=0U;
    static const uint8_t complete[]="HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\n\r\n19\r\ndata: {\"response\":\"ok\"}\n\n\r\ne\r\ndata: [DONE]\n\n\r\n0\r\n\r\n";
    static const uint8_t first[]="HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\n\r\n19\r\ndata: {\"response\":\"go\"}\n\n\r\n";
    static const uint8_t rest[]="e\r\ndata: [DONE]\n\n\r\n0\r\n\r\n";
    TEST_ASSERT_EQUAL(0,net_llm_sse_response_init(&response,http_buffer,sizeof(http_buffer),sse_buffer,sizeof(sse_buffer)));
    TEST_ASSERT_EQUAL(0,net_llm_sse_response_feed(&response,0U,complete,sizeof(complete)-1U,text,sizeof(text),&text_length));
    TEST_ASSERT_EQUAL(2U,text_length);TEST_ASSERT_EQUAL(8U,response.http.state);
    TEST_ASSERT_NOT_EQUAL(0,net_llm_sse_response_feed(&response,0U,first,sizeof(first)-1U,text,sizeof(text),&text_length));
    TEST_ASSERT_EQUAL(0,net_llm_sse_response_init(&response,http_buffer,sizeof(http_buffer),sse_buffer,sizeof(sse_buffer)));
    TEST_ASSERT_EQUAL(1,net_llm_sse_response_feed(&response,0U,first,sizeof(first)-1U,text,sizeof(text),&text_length));
    TEST_ASSERT_EQUAL(2U,text_length);TEST_ASSERT_EQUAL_MEMORY("go",text,2U);
    TEST_ASSERT_EQUAL(0,net_llm_sse_response_feed(&response,0U,rest,sizeof(rest)-1U,text,sizeof(text),&text_length));
    TEST_ASSERT_EQUAL(1U,response.sse.done);TEST_ASSERT_EQUAL(8U,response.http.state);
}

void test_llm_unicode_utf8_bounded(void){uint8_t output[96]={0},json[96]={0};uint16_t length=0U;static const uint8_t encoded[]="{\"response\":\"caf\\u00e9 \\ud83d\\ude00\"}";static const uint8_t expected[]={'c','a','f',0xc3U,0xa9U,' ',0xf0U,0x9fU,0x98U,0x80U};static const uint8_t prompt[]={'c','a','f',0xc3U,0xa9U};static const uint8_t invalid[]={'x',0xc3U};TEST_ASSERT_EQUAL(0,net_json_extract_string(encoded,sizeof(encoded)-1U,"response",output,sizeof(output),&length));TEST_ASSERT_EQUAL(sizeof(expected),length);TEST_ASSERT_EQUAL_MEMORY(expected,output,sizeof(expected));TEST_ASSERT_TRUE(net_llm_build_ollama_generate_json(json,sizeof(json),"tinyllama",prompt,sizeof(prompt))>0);TEST_ASSERT_NOT_EQUAL(0,net_llm_build_ollama_generate_json(json,sizeof(json),"tinyllama",invalid,sizeof(invalid)));}



void test_llm_large_fragmented_unicode_response(void){
    net_http_response_accumulator_t accumulator;net_http_response_view_t response;uint8_t wire[1200]={0},body[1024]={0},output[1024]={0};uint16_t body_length=1015U,first_length=300U,text_length=0U,index=0U;int status;
    static const uint8_t prefix[]={"{\"response\":\""};static const uint8_t suffix[]={'"','}'};static const uint8_t emoji[]={0xf0U,0x9fU,0x98U,0x80U};
    for(index=0U;index<sizeof(prefix)-1U;index++)body[index]=prefix[index];
    for(;index<sizeof(prefix)-1U+996U;index++)body[index]='a';
    for(index=0U;index<sizeof(emoji);index++)body[sizeof(prefix)-1U+996U+index]=emoji[index];
    body[sizeof(prefix)-1U+996U+sizeof(emoji)]=suffix[0];body[sizeof(prefix)-1U+996U+sizeof(emoji)+1U]=suffix[1];
    {static const uint8_t header[]={"HTTP/1.1 200 OK\r\nContent-Length: 1015\r\n\r\n"};for(index=0U;index<sizeof(header)-1U;index++)wire[index]=header[index];for(index=0U;index<body_length;index++)wire[(sizeof(header)-1U)+index]=body[index];}
    TEST_ASSERT_EQUAL(0,net_http_response_accumulator_init(&accumulator,wire,sizeof(wire)));status=net_http_response_accumulator_feed(&accumulator,wire,first_length,&response);TEST_ASSERT_EQUAL(1,status);status=net_http_response_accumulator_feed(&accumulator,wire+first_length,(uint16_t)((sizeof("HTTP/1.1 200 OK\r\nContent-Length: 1015\r\n\r\n")-1U)+body_length-first_length),&response);TEST_ASSERT_EQUAL(0,status);TEST_ASSERT_EQUAL(200,response.status_code);TEST_ASSERT_EQUAL(1000U,response.body_length-13U-2U);TEST_ASSERT_EQUAL(0,net_llm_ollama_response_extract(response.body,response.body_length,output,sizeof(output),&text_length));TEST_ASSERT_EQUAL(1000U,text_length);TEST_ASSERT_EQUAL('a',output[995]);TEST_ASSERT_EQUAL_MEMORY(emoji,output+996U,sizeof(emoji));
}


void test_llm_large_utf8_prompt_builder(void){
    uint8_t prompt[1020]={0},json[1152]={0};uint16_t index;int length;
    for(index=0U;index<1016U;index++)prompt[index]='a';
    prompt[1016U]=0xf0U;prompt[1017U]=0x9fU;prompt[1018U]=0x98U;prompt[1019U]=0x80U;
    length=net_llm_build_ollama_generate_json(json,sizeof(json),"tinyllama",prompt,sizeof(prompt));
    TEST_ASSERT_GREATER_THAN(0,length);TEST_ASSERT_NOT_EQUAL(0,net_llm_build_ollama_generate_json(json,1024U,"tinyllama",prompt,sizeof(prompt)));
}


void test_llm_sse_multiline_and_split_utf8(void){
    net_llm_sse_accumulator_t accumulator,multiline;uint8_t buffer[128]={0},second_buffer[128]={0},text[64]={0};uint16_t text_length=0U;
    static const uint8_t first[]={"data: {\"response\":\"caf\xf0"};static const uint8_t second[]={0x9fU,0x98U,0x80U,'"','}', '\n','\n'};static const uint8_t joined[]={"data: {\"response\":\"bon\ndata: jour\"}\n\n"};
    TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_init(&accumulator,buffer,sizeof(buffer)));TEST_ASSERT_EQUAL(1,net_llm_sse_accumulator_feed(&accumulator,0U,first,sizeof(first)-1U,text,sizeof(text),&text_length));TEST_ASSERT_EQUAL(0U,text_length);TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_feed(&accumulator,0U,second,sizeof(second),text,sizeof(text),&text_length));TEST_ASSERT_EQUAL(7U,text_length);TEST_ASSERT_EQUAL_MEMORY("caf",text,3U);TEST_ASSERT_EQUAL_MEMORY("\xf0\x9f\x98\x80",text+3U,4U);TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_init(&multiline,second_buffer,sizeof(second_buffer)));TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_feed(&multiline,0U,joined,sizeof(joined)-1U,text,sizeof(text),&text_length));TEST_ASSERT_EQUAL(7U,text_length);TEST_ASSERT_EQUAL_MEMORY("bonjour",text,7U);
}
void test_llm_http_retry_bounded_backoff(void){uint8_t retries=0U;uint32_t retry_at=0U;TEST_ASSERT_EQUAL(1,net_llm_http_retry_schedule(503U,3U,10U,25U,100U,&retries,&retry_at));TEST_ASSERT_EQUAL(110U,retry_at);TEST_ASSERT_EQUAL(1,net_llm_http_retry_schedule(429U,3U,10U,25U,110U,&retries,&retry_at));TEST_ASSERT_EQUAL(130U,retry_at);TEST_ASSERT_EQUAL(1,net_llm_http_retry_schedule(500U,3U,10U,25U,130U,&retries,&retry_at));TEST_ASSERT_EQUAL(155U,retry_at);TEST_ASSERT_EQUAL(0,net_llm_http_retry_schedule(503U,3U,10U,25U,155U,&retries,&retry_at));retries=0U;retry_at=77U;TEST_ASSERT_NOT_EQUAL(0,net_llm_http_retry_schedule(503U,3U,0U,25U,100U,&retries,&retry_at));TEST_ASSERT_EQUAL(0U,retries);TEST_ASSERT_EQUAL(77U,retry_at);}
void test_llm_bearer_store_lifecycle(void){net_llm_bearer_store_t store={0};uint8_t request[256]={0};static const uint8_t json[]={'{','"','x','"',':','1','}'};static const uint8_t token[]="sk-test-store";static const uint8_t invalid[]={'x','\n'};int length;uint16_t index;TEST_ASSERT_EQUAL(0,net_llm_bearer_store_provision(&store,token,sizeof(token)-1U));TEST_ASSERT_EQUAL(1U,store.provisioned);length=net_http_build_post_json_bearer_store(request,sizeof(request),"api.example.test","/v1/chat",&store,json,sizeof(json));TEST_ASSERT_GREATER_THAN(0,length);TEST_ASSERT_NOT_EQUAL(0,net_llm_bearer_store_provision(&store,invalid,sizeof(invalid)));TEST_ASSERT_NOT_EQUAL(0,net_llm_bearer_store_provision(&store,token,NET_LLM_BEARER_MAX));net_llm_bearer_store_clear(&store);TEST_ASSERT_EQUAL(0U,store.provisioned);TEST_ASSERT_EQUAL(0U,store.length);for(index=0U;index<NET_LLM_BEARER_MAX;index++)TEST_ASSERT_EQUAL(0U,store.token[index]);}
void test_http_tls_post_json_bearer_store_encrypted(void){net_tcp_connection_t client,server;net_tls_aes_gcm_session_t client_session,server_session;net_tcp_view_t view;net_tls_record_view_t record;net_llm_bearer_store_t store={0};static const uint8_t token[]="sk-store-tls";static const uint8_t json[]={ '{','"','x','"',':','1','}' };static const uint8_t expected[]="POST /v1/chat HTTP/1.1\r\nHost: api.example.test\r\nAuthorization: Bearer sk-store-tls\r\nContent-Type: application/json\r\nContent-Length: 7\r\nConnection: close\r\n\r\n{\"x\":1}";uint8_t key_material[40]={0},tcp_segment[320]={0},tls_record[288]={0},request[256]={0},plaintext[256]={0};uint16_t consumed=0U;int length;TEST_ASSERT_EQUAL(0,net_llm_bearer_store_provision(&store,token,sizeof(token)-1U));open_pair(&client,&server,&client_session,&server_session,key_material);length=net_http_tls_build_post_json_bearer_store(&client,&client_session,tcp_segment,sizeof(tcp_segment),tls_record,sizeof(tls_record),request,sizeof(request),"api.example.test","/v1/chat",&store,json,sizeof(json),1U);TEST_ASSERT_GREATER_THAN(0,length);TEST_ASSERT_EQUAL(0,net_tcp_parse(tcp_segment,(uint16_t)length,&view));TEST_ASSERT_EQUAL(0,net_tcp_connection_accept_tls_aes_gcm(&server,&server_session,&view,plaintext,sizeof(plaintext),&record,&consumed));TEST_ASSERT_EQUAL(sizeof(expected)-1U,record.payload_length);TEST_ASSERT_EQUAL_MEMORY(expected,plaintext,sizeof(expected)-1U);net_llm_bearer_store_clear(&store);}

void test_llm_sse_reconnect_scheduler(void){net_llm_sse_response_t response;net_llm_sse_reconnect_t reconnect;uint8_t http_buffer[128]={0},sse_buffer[64]={0};TEST_ASSERT_EQUAL(0,net_llm_sse_response_init(&response,http_buffer,sizeof(http_buffer),sse_buffer,sizeof(sse_buffer)));response.http.length=4U;response.sse.length=3U;TEST_ASSERT_EQUAL(0,net_llm_sse_reconnect_init(&reconnect,2U));TEST_ASSERT_EQUAL(1,net_llm_sse_reconnect_schedule(&reconnect,&response,503U,10U,25U,100U));TEST_ASSERT_EQUAL(1U,reconnect.retries_used);TEST_ASSERT_EQUAL(110U,reconnect.next_tick);TEST_ASSERT_EQUAL(0U,response.http.length);TEST_ASSERT_EQUAL(0U,response.sse.length);TEST_ASSERT_EQUAL(0,net_llm_sse_reconnect_ready(&reconnect,109U));TEST_ASSERT_EQUAL(1,net_llm_sse_reconnect_ready(&reconnect,110U));TEST_ASSERT_EQUAL(1,net_llm_sse_reconnect_schedule(&reconnect,&response,429U,10U,25U,110U));TEST_ASSERT_EQUAL(2U,reconnect.retries_used);TEST_ASSERT_EQUAL(130U,reconnect.next_tick);TEST_ASSERT_EQUAL(0,net_llm_sse_reconnect_schedule(&reconnect,&response,503U,10U,25U,130U));TEST_ASSERT_EQUAL(0,net_llm_sse_reconnect_schedule(&reconnect,&response,200U,10U,25U,130U));}

 void test_llm_sse_retry_hint_applied_to_scheduler(void){net_llm_sse_response_t response;net_llm_sse_reconnect_t reconnect;uint8_t http_buffer[128]={0},sse_buffer[64]={0};TEST_ASSERT_EQUAL(0,net_llm_sse_response_init(&response,http_buffer,sizeof(http_buffer),sse_buffer,sizeof(sse_buffer)));response.sse.retry_valid=1U;response.sse.retry_delay_ms=1500U;TEST_ASSERT_EQUAL(0,net_llm_sse_reconnect_init(&reconnect,3U));TEST_ASSERT_EQUAL(1,net_llm_sse_reconnect_schedule(&reconnect,&response,503U,10U,2500U,100U));TEST_ASSERT_EQUAL(1600U,reconnect.next_tick);TEST_ASSERT_EQUAL(0U,response.sse.retry_valid);TEST_ASSERT_EQUAL(1,net_llm_sse_reconnect_schedule(&reconnect,&response,503U,10U,25U,1600U));TEST_ASSERT_EQUAL(1620U,reconnect.next_tick);response.sse.retry_valid=1U;response.sse.retry_delay_ms=600000U;TEST_ASSERT_EQUAL(1,net_llm_sse_reconnect_schedule(&reconnect,&response,503U,10U,25U,1620U));TEST_ASSERT_EQUAL(1645U,reconnect.next_tick);}

void test_llm_sse_last_event_id_resume(void){
    net_llm_sse_accumulator_t accumulator;net_llm_sse_response_t response;uint8_t sse_buffer[128]={0},http_buffer[128]={0},text[32]={0},request[192]={0};uint16_t text_length=0U;int resume_length;
    static const uint8_t input[]={"id: 42\ndata: {\"response\":\"ok\"}\n\n"};static const uint8_t expected[]={"GET /v1/chat HTTP/1.1\r\nHost: api.example.test\r\nLast-Event-ID: 42\r\nConnection: close\r\n\r\n"};
    TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_init(&accumulator,sse_buffer,sizeof(sse_buffer)));
    TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_feed(&accumulator,0U,input,sizeof(input)-1U,text,sizeof(text),&text_length));
    TEST_ASSERT_EQUAL(2U,text_length);TEST_ASSERT_EQUAL_MEMORY("ok",text,2U);
    TEST_ASSERT_EQUAL(1U,accumulator.event_id_valid);TEST_ASSERT_EQUAL(2U,accumulator.event_id_length);TEST_ASSERT_EQUAL_MEMORY("42",accumulator.event_id,2U);
    resume_length=net_http_build_sse_resume_get(request,sizeof(request),"api.example.test","/v1/chat",accumulator.event_id,accumulator.event_id_length);TEST_ASSERT_EQUAL((int)(sizeof(expected)-1U),resume_length);
    TEST_ASSERT_EQUAL_MEMORY(expected,request,sizeof(expected)-1U);
    TEST_ASSERT_EQUAL(0,net_llm_sse_response_init(&response,http_buffer,sizeof(http_buffer),sse_buffer,sizeof(sse_buffer)));response.sse=accumulator;
    TEST_ASSERT_EQUAL(0,net_llm_sse_response_reset(&response));TEST_ASSERT_EQUAL(1U,response.sse.event_id_valid);TEST_ASSERT_EQUAL(2U,response.sse.event_id_length);TEST_ASSERT_EQUAL_MEMORY("42",response.sse.event_id,2U);
    TEST_ASSERT_EQUAL((int)(sizeof(expected)-1U),net_llm_sse_build_resume_get(request,sizeof(request),"api.example.test","/v1/chat",&response));
}

void test_llm_sse_retry_hint_bounded(void){net_llm_sse_accumulator_t accumulator;uint8_t buffer[128]={0},text[32]={0};uint16_t text_length=0U;static const uint8_t event[]={"retry: 1500\ndata: {\"response\":\"ok\"}\n\n"};static const uint8_t invalid[]={"retry: 600001\ndata: {\"response\":\"bad\"}\n\n"};TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_init(&accumulator,buffer,sizeof(buffer)));TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_feed(&accumulator,0U,event,sizeof(event)-1U,text,sizeof(text),&text_length));TEST_ASSERT_EQUAL(1U,accumulator.retry_valid);TEST_ASSERT_EQUAL(1500U,accumulator.retry_delay_ms);TEST_ASSERT_EQUAL(2U,text_length);TEST_ASSERT_EQUAL_MEMORY("ok",text,2U);TEST_ASSERT_EQUAL(0,net_llm_sse_accumulator_init(&accumulator,buffer,sizeof(buffer)));TEST_ASSERT_NOT_EQUAL(0,net_llm_sse_accumulator_feed(&accumulator,0U,invalid,sizeof(invalid)-1U,text,sizeof(text),&text_length));TEST_ASSERT_EQUAL(0U,accumulator.retry_valid);}

void test_llm_sse_jittered_retry_schedule(void){net_llm_sse_reconnect_t reconnect={0};net_llm_sse_response_t response={0};uint8_t http_buffer[32]={0},sse_buffer[32]={0};uint32_t seed=1U;TEST_ASSERT_EQUAL(0,net_llm_sse_response_init(&response,http_buffer,sizeof(http_buffer),sse_buffer,sizeof(sse_buffer)));TEST_ASSERT_EQUAL(0,net_llm_sse_reconnect_init(&reconnect,2U));TEST_ASSERT_EQUAL(1,net_llm_sse_reconnect_schedule_jittered(&reconnect,&response,503U,10U,100U,100U,5U,&seed));TEST_ASSERT_TRUE(reconnect.next_tick>=101U);TEST_ASSERT_TRUE(reconnect.next_tick<=115U);TEST_ASSERT_NOT_EQUAL(1,net_llm_sse_reconnect_schedule_jittered(&reconnect,&response,503U,0U,100U,100U,5U,&seed));}
void test_llm_sse_persist_roundtrip_and_integrity(void){net_llm_sse_response_t source={0},loaded={0};net_llm_sse_persisted_state_t persisted={0};uint8_t source_http[32]={0},source_sse[32]={0},loaded_http[32]={0},loaded_sse[32]={0},provider=0,retries=0;TEST_ASSERT_EQUAL(0,net_llm_sse_response_init(&source,source_http,sizeof(source_http),source_sse,sizeof(source_sse)));source.sse.event_id[0]='e';source.sse.event_id[1]='v';source.sse.event_id[2]='t';source.sse.event_id[3]='-';source.sse.event_id[4]='7';source.sse.event_id_length=5U;source.sse.event_id_valid=1U;TEST_ASSERT_EQUAL(0,net_llm_sse_persist_save(&persisted,1U,3U,&source));TEST_ASSERT_EQUAL(0,net_llm_sse_response_init(&loaded,loaded_http,sizeof(loaded_http),loaded_sse,sizeof(loaded_sse)));TEST_ASSERT_EQUAL(0,net_llm_sse_persist_load(&persisted,&provider,&retries,&loaded));TEST_ASSERT_EQUAL(1U,provider);TEST_ASSERT_EQUAL(3U,retries);TEST_ASSERT_EQUAL(5U,loaded.sse.event_id_length);persisted.event_id[0]^=1U;TEST_ASSERT_EQUAL(-2,net_llm_sse_persist_load(&persisted,&provider,&retries,&loaded));}
void test_llm_model_policy_validation(void){net_llm_model_policy_t policy={0,"tiny-model",10U,1U};TEST_ASSERT_EQUAL(0,net_llm_model_policy_validate(&policy));policy.model_length=0U;TEST_ASSERT_NOT_EQUAL(0,net_llm_model_policy_validate(&policy));policy.model_length=10U;policy.provider=9U;TEST_ASSERT_NOT_EQUAL(0,net_llm_model_policy_validate(&policy));}
void test_http_tls_response_stream_peer_close_notify(void){net_tcp_connection_t client,server;net_tls_aes_gcm_session_t client_session,server_session;net_tcp_view_t view;net_http_response_accumulator_t accumulator;net_http_response_view_t response;uint8_t key_material[40]={0},record[48]={0},segment[80]={0},plaintext[8]={0},buffer[32]={0};uint16_t consumed=0U;int length;open_pair(&client,&server,&client_session,&server_session,key_material);TEST_ASSERT_EQUAL(0,net_http_response_accumulator_init(&accumulator,buffer,sizeof(buffer)));length=net_tls_close_notify_build(&server_session,record,sizeof(record));TEST_ASSERT_EQUAL(31,length);length=net_tcp_connection_build_data(&server,segment,sizeof(segment),record,(uint16_t)length,1U);TEST_ASSERT_GREATER_THAN(0,length);TEST_ASSERT_EQUAL(0,net_tcp_parse(segment,(uint16_t)length,&view));TEST_ASSERT_EQUAL(NET_HTTP_TLS_STATUS_CLOSE_NOTIFY,net_http_tls_open_response_stream(&client,&client_session,&view,plaintext,sizeof(plaintext),&accumulator,&response,&consumed));TEST_ASSERT_EQUAL(1U,client_session.read_sequence);TEST_ASSERT_EQUAL(31U,consumed);TEST_ASSERT_EQUAL(0U,accumulator.length);}
void test_http_tls_sse_stream_peer_close_notify(void){net_tcp_connection_t client,server;net_tls_aes_gcm_session_t client_session,server_session;net_tcp_view_t view;net_llm_sse_response_t response;uint8_t key_material[40]={0},record[48]={0},segment[80]={0},plaintext[8]={0},http_buffer[32]={0},sse_buffer[32]={0},text[8]={0};uint16_t consumed=0U,text_length=7U;int length;open_pair(&client,&server,&client_session,&server_session,key_material);TEST_ASSERT_EQUAL(0,net_llm_sse_response_init(&response,http_buffer,sizeof(http_buffer),sse_buffer,sizeof(sse_buffer)));length=net_tls_close_notify_build(&server_session,record,sizeof(record));TEST_ASSERT_EQUAL(31,length);length=net_tcp_connection_build_data(&server,segment,sizeof(segment),record,(uint16_t)length,1U);TEST_ASSERT_GREATER_THAN(0,length);TEST_ASSERT_EQUAL(0,net_tcp_parse(segment,(uint16_t)length,&view));TEST_ASSERT_EQUAL(NET_HTTP_TLS_STATUS_CLOSE_NOTIFY,net_http_tls_open_sse_stream(&client,&client_session,&view,plaintext,sizeof(plaintext),&response,0U,text,sizeof(text),&text_length,&consumed));TEST_ASSERT_EQUAL(1U,client_session.read_sequence);TEST_ASSERT_EQUAL(31U,consumed);TEST_ASSERT_EQUAL(7U,text_length);TEST_ASSERT_EQUAL(0U,response.http.length);}
int main(void){unity_init();RUN_TEST(test_http_tls_get_and_response);RUN_TEST(test_http_post_json_build_and_bounds);RUN_TEST(test_http_post_json_bearer_build_and_bounds);RUN_TEST(test_http_tls_post_json_encrypted);RUN_TEST(test_http_tls_response_stream_content_length);RUN_TEST(test_http_chunked_accumulator_fragmented);RUN_TEST(test_llm_json_string_extract);RUN_TEST(test_llm_provider_response_adapters);RUN_TEST(test_llm_request_json_builders);RUN_TEST(test_llm_http_status_and_retry_policy);RUN_TEST(test_http_response_parse_rejects_invalid_framing);RUN_TEST(test_llm_stream_json_and_sse_fragments);RUN_TEST(test_llm_sse_chunked_openai_response);RUN_TEST(test_llm_sse_chunked_ollama_incremental);RUN_TEST(test_llm_sse_second_stream_after_reinit);RUN_TEST(test_llm_unicode_utf8_bounded);RUN_TEST(test_llm_large_fragmented_unicode_response);RUN_TEST(test_llm_large_utf8_prompt_builder);RUN_TEST(test_llm_sse_multiline_and_split_utf8);RUN_TEST(test_llm_http_retry_bounded_backoff);RUN_TEST(test_llm_bearer_store_lifecycle);RUN_TEST(test_http_tls_post_json_bearer_store_encrypted);RUN_TEST(test_llm_sse_reconnect_scheduler);RUN_TEST(test_llm_sse_retry_hint_applied_to_scheduler);RUN_TEST(test_llm_sse_last_event_id_resume);RUN_TEST(test_llm_sse_retry_hint_bounded);RUN_TEST(test_llm_sse_jittered_retry_schedule);RUN_TEST(test_llm_sse_persist_roundtrip_and_integrity);RUN_TEST(test_llm_model_policy_validation);RUN_TEST(test_http_tls_response_stream_peer_close_notify);RUN_TEST(test_http_tls_sse_stream_peer_close_notify);unity_print_results();unity_cleanup();return unity_stats.tests_failed==0?0:1;}
